#include "kernel/initrd.h"
#include "fs/vfs.h"
#include "lib/printf.h"

/* Symbols generated by objcopy -I binary from build/user/hello.elf */
extern uint8_t _binary_build_user_hello_elf_start[];
extern uint8_t _binary_build_user_hello_elf_end[];

void initrd_init(void) {
    uint32_t hello_size = (uint32_t)(_binary_build_user_hello_elf_end - _binary_build_user_hello_elf_start);

    /* Create /bin directory */
    vfs_mkdir("/bin");

    /* Write hello ELF into /bin/hello */
    int fd = vfs_open("/bin/hello", VFS_O_CREATE);
    if (fd < 0) {
        kprintf("[INITRD] Failed to create /bin/hello\n");
        return;
    }
    vfs_write(fd, _binary_build_user_hello_elf_start, hello_size);
    vfs_close(fd);

    kprintf("[INITRD] Embedded '/bin/hello' (%u bytes)\n", hello_size);
}
